import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Docs Overview',
      items: ['overview/intro'],
    },
    {
      type: 'category',
      label: 'Event Sourcing',
      link: {type: 'doc', id: 'event-sourcing/index'},
      items: [{type: 'autogenerated', dirName: 'event-sourcing'}],
    },
    {
      type: 'category',
      label: 'Event Store',
      link: {type: 'doc', id: 'event-store/index'},
      items: [
        {type: 'autogenerated', dirName: 'event-store/adrs'},
        {type: 'autogenerated', dirName: 'event-store/concepts'},
        {type: 'autogenerated', dirName: 'event-store/development'},
        {type: 'autogenerated', dirName: 'event-store/implementation'},
        {type: 'autogenerated', dirName: 'event-store/operations'},
        {type: 'autogenerated', dirName: 'event-store/sdks'},
      ],
    },
    {
      type: 'category',
      label: 'VSA Manager',
      link: {type: 'doc', id: 'vsa/index'},
      items: [
        {type: 'autogenerated', dirName: 'vsa/getting-started'},
        {type: 'autogenerated', dirName: 'vsa/concepts'},
        {type: 'autogenerated', dirName: 'vsa/cli'},
        {type: 'autogenerated', dirName: 'vsa/ide'},
        {type: 'autogenerated', dirName: 'vsa/examples'},
        {type: 'autogenerated', dirName: 'vsa/advanced'},
        {type: 'autogenerated', dirName: 'vsa/api'},
        {type: 'autogenerated', dirName: 'vsa/guides'},
      ],
    },
    {
      type: 'category',
      label: 'Shared Concepts',
      link: {type: 'doc', id: 'concepts/overview'},
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Development',
      link: {type: 'generated-index', description: 'Development guides for fast iteration and feedback.'},
      items: [{type: 'autogenerated', dirName: 'development'}],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      link: {type: 'generated-index', description: 'Infrastructure as Code guides for deploying the platform.'},
      items: [
        'infra/architecture-decisions',
        'infra/proxmox-terraform-deployment',
      ],
    },
  ],
};

export default sidebars;
