import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Docs Overview',
      items: ['overview/intro'],
    },
    {
      type: 'category',
      label: 'Event Sourcing',
      link: {type: 'doc', id: 'event-sourcing/index'},
      items: [{type: 'autogenerated', dirName: 'event-sourcing'}],
    },
    {
      type: 'category',
      label: 'Event Store',
      link: {type: 'doc', id: 'event-store/event-store-index'},
      items: [{type: 'autogenerated', dirName: 'event-store'}],
    },
    {
      type: 'category',
      label: 'Shared Concepts',
      link: {type: 'doc', id: 'concepts/overview'},
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Development',
      link: {type: 'generated-index', description: 'Development guides for fast iteration and feedback.'},
      items: [{type: 'autogenerated', dirName: 'development'}],
    },
  ],
};

export default sidebars;
