"""Cross-language peer for the Rust SDK wire-format tests (ADR-027).

Uses the real Python SDK (aggregate -> EventStoreRepository ->
GrpcEventStoreClient) so the bytes are exactly what a Python application
writes.

    uv run --project <python-sdk> --extra grpc python py_peer.py capture <out.json>
    ... py_peer.py write <addr> <tenant> <id>   append the fixture stream
    ... py_peer.py read <addr> <tenant> <id>    print the decoded stream as JSON
"""

from __future__ import annotations

import asyncio
import base64
import json
import sys
from datetime import UTC, datetime
from typing import ClassVar

from google.protobuf import json_format

import event_sourcing.core.event as core_event
from event_sourcing.client.grpc_client import GrpcEventStoreClient
from event_sourcing.core.aggregate import AggregateRoot
from event_sourcing.core.event import DomainEvent
from event_sourcing.core.repository import EventStoreRepository
from event_sourcing.decorators.events import event
from event_sourcing.proto.eventstore.v1 import eventstore_pb2


# Fixture domain (mirrors tests/common/xlang.rs). Strict models
# (extra="forbid"): reading proves a payload holds exactly the schema's fields.
@event("AccountOpened", "v1")
class AccountOpened(DomainEvent):
    event_type: ClassVar[str] = "AccountOpened"
    account_id: str
    owner: str


@event("MoneyDeposited", "v1")
class MoneyDeposited(DomainEvent):
    event_type: ClassVar[str] = "MoneyDeposited"
    amount: int
    note: str


@event("AccountClosed", "v2")
class AccountClosed(DomainEvent):
    event_type: ClassVar[str] = "AccountClosed"
    schema_version: ClassVar[int] = 2
    reason: str
    tags: list[str]


class Account(AggregateRoot[DomainEvent]):
    def get_aggregate_type(self) -> str:
        return "Account"

    def apply_event(self, event: DomainEvent) -> None:  # state is irrelevant here
        pass

    def run(self, aggregate_id: str) -> None:
        self._initialize(aggregate_id)
        self._raise_event(AccountOpened(account_id=aggregate_id, owner="alice"))
        self._raise_event(MoneyDeposited(amount=125, note='café ☕ "quoted"'))
        self._raise_event(AccountClosed(reason="done", tags=["a", "b"]))


def freeze() -> None:
    """Deterministic ids and clock for the golden capture."""
    counter = iter(range(1, 100))

    class FixedDatetime(datetime):
        @classmethod
        def now(cls, tz=None):  # noqa: ANN001, ANN206
            return datetime(2026, 1, 2, 3, 4, 5, 678000, tzinfo=UTC)

    core_event.uuid4 = lambda: f"00000000-0000-4000-8000-0000000001{next(counter):02d}"  # type: ignore[assignment]
    core_event.datetime = FixedDatetime  # type: ignore[misc]


class CaptureStub:
    def __init__(self) -> None:
        self.request = None

    async def Append(self, request):  # noqa: N802, ANN001, ANN201
        self.request = request

        class Resp:
            last_global_nonce = 3
            last_aggregate_nonce = 3

        return Resp()


async def capture(out: str) -> None:
    freeze()
    client = GrpcEventStoreClient(address="127.0.0.1:1", tenant_id="tenant-golden")
    stub = CaptureStub()
    client._stub = stub  # type: ignore[assignment]
    repo = EventStoreRepository(client, Account, "Account")
    acct = Account()
    acct.run("acct-py-1")
    await repo.save(acct)
    req = stub.request
    fixture = {
        "producer": "python",
        "note": "Generated by event-sourcing/rust/tests/xlang/py_peer.py capture. Do not edit.",
        "append_request_base64": base64.b64encode(req.SerializeToString(deterministic=True)).decode(),
        "append_request": json_format.MessageToDict(req),
        "payloads": [e.payload.decode("utf-8") for e in req.events],
    }
    with open(out, "w", encoding="utf-8") as f:
        f.write(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n")


async def write(addr: str, tenant: str, aggregate_id: str) -> None:
    client = GrpcEventStoreClient(address=addr, tenant_id=tenant)
    await client.connect()
    acct = Account()
    acct.run(aggregate_id)
    await EventStoreRepository(client, Account, "Account").save(acct)
    await client.disconnect()


async def read(addr: str, tenant: str, aggregate_id: str) -> None:
    client = GrpcEventStoreClient(address=addr, tenant_id=tenant)
    await client.connect()
    envelopes = await client.read_events(f"Account-{aggregate_id}")
    # The wire metadata too, so the test can check what the SDK reports.
    raw = await client._stub.ReadStream(  # type: ignore[union-attr]
        eventstore_pb2.ReadStreamRequest(
            tenant_id=tenant,
            aggregate_id=aggregate_id,
            from_aggregate_nonce=1,
            max_count=1000,
            forward=True,
        )
    )
    await client.disconnect()
    out = []
    for env, data in zip(envelopes, raw.events, strict=True):
        m = env.metadata
        out.append(
            {
                "event_type": m.event_type,
                "event_version": m.event_version,
                "stored_event_type": m.stored_event_type,
                "stored_event_version": m.stored_event_version,
                "wire_event_type": data.meta.event_type,
                "wire_event_version": data.meta.event_version,
                "class": type(env.event).__name__,
                "aggregate_type": m.aggregate_type,
                "aggregate_nonce": m.aggregate_nonce,
                "content_type": m.content_type,
                "data": env.event.model_dump(mode="json"),
            }
        )
    sys.stdout.write(json.dumps(out))


def main() -> None:
    cmd, *args = sys.argv[1:]
    fn = {"capture": capture, "write": write, "read": read}.get(cmd)
    if fn is None:
        sys.exit("usage: py_peer.py capture <out> | write|read <addr> <tenant> <id>")
    asyncio.run(fn(*args))


if __name__ == "__main__":
    main()
