#!/usr/bin/env node
// Cross-language peer for the Rust SDK wire-format tests (ADR-026).
//
// Uses the real TypeScript SDK (aggregate -> EventStoreRepository ->
// GrpcEventStoreAdapter -> @eventstore/sdk-ts) so the bytes are exactly what
// a TypeScript application writes.
//
//   node ts_peer.cjs capture <out.json>       golden AppendRequest, no server
//   node ts_peer.cjs write <addr> <tenant> <id>  append the fixture stream
//   node ts_peer.cjs read <addr> <tenant> <id>   print the decoded stream as JSON
//
// Requires `pnpm install` at the repo root (builds the TS SDK).
'use strict';

const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');

const tsRoot = path.resolve(__dirname, '../../../typescript');
const es = require(path.join(tsRoot, 'dist/index.js'));
const sdkTsEntry = fs.realpathSync(
  path.join(tsRoot, 'node_modules/@eventstore/sdk-ts/dist/index.js')
);
const sdkTsGen = path.join(path.dirname(sdkTsEntry), 'gen/eventstore/v1/eventstore.js');

// ---------------------------------------------------------------------------
// Fixture domain (mirrors tests/xlang_golden.rs)
// ---------------------------------------------------------------------------

class AccountOpened extends es.BaseDomainEvent {
  constructor(account_id, owner) {
    super();
    this.eventType = 'AccountOpened';
    this.schemaVersion = 1;
    this.account_id = account_id;
    this.owner = owner;
  }
}
es.Event('AccountOpened', 'v1')(AccountOpened);

class MoneyDeposited extends es.BaseDomainEvent {
  constructor(amount, note) {
    super();
    this.eventType = 'MoneyDeposited';
    this.schemaVersion = 1;
    this.amount = amount;
    this.note = note;
  }
}
es.Event('MoneyDeposited', 'v1')(MoneyDeposited);

class AccountClosed extends es.BaseDomainEvent {
  constructor(reason, tags) {
    super();
    this.eventType = 'AccountClosed';
    this.schemaVersion = 2;
    this.reason = reason;
    this.tags = tags;
  }
}
es.Event('AccountClosed', 'v2')(AccountClosed);

class Account extends es.AggregateRoot {
  getAggregateType() {
    return 'Account';
  }
  applyEvent() {}
  run(id) {
    this.initialize(id);
    this.raiseEvent(new AccountOpened(id, 'alice'));
    this.raiseEvent(new MoneyDeposited(125, 'café ☕ "quoted"'));
    this.raiseEvent(new AccountClosed('done', ['a', 'b']));
  }
}

function repo(addr, tenant) {
  const adapter = new es.GrpcEventStoreAdapter({ serverAddress: addr, tenantId: tenant });
  return { adapter, repo: new es.EventStoreRepository(adapter, () => new Account(), 'Account') };
}

// Deterministic ids and clock for the golden capture.
function freeze() {
  let n = 0;
  const ids = () => `00000000-0000-4000-8000-0000000000${String(++n).padStart(2, '0')}`;
  Object.defineProperty(globalThis.crypto, 'randomUUID', { value: ids, configurable: true });
  const fixed = Date.UTC(2026, 0, 2, 3, 4, 5, 678);
  const RealDate = Date;
  globalThis.Date = class extends RealDate {
    constructor(...args) {
      super(...(args.length ? args : [fixed]));
    }
    static now() {
      return fixed;
    }
  };
}

async function capture(out) {
  freeze();
  const sdk = await import(pathToFileURL(sdkTsEntry).href);
  const gen = await import(pathToFileURL(sdkTsGen).href);
  let captured;
  sdk.EventStoreClientTS.prototype.append = async function (req) {
    captured = req;
    return { lastGlobalNonce: 3, lastAggregateNonce: 3 };
  };
  const { repo: r } = repo('127.0.0.1:1', 'tenant-golden');
  const acct = new Account();
  acct.run('acct-ts-1');
  await r.save(acct);
  const bytes = gen.AppendRequest.encode(captured).finish();
  writeFixture(out, 'typescript', Buffer.from(bytes), gen.AppendRequest.toJSON(captured));
}

function writeFixture(out, producer, bytes, json) {
  const fixture = {
    producer,
    note: 'Generated by event-sourcing/rust/tests/xlang/ts_peer.cjs capture. Do not edit.',
    append_request_base64: bytes.toString('base64'),
    append_request: json,
    payloads: json.events.map((e) => Buffer.from(e.payload, 'base64').toString('utf8')),
  };
  fs.writeFileSync(out, JSON.stringify(fixture, null, 2) + '\n');
}

async function write(addr, tenant, id) {
  const { repo: r } = repo(addr, tenant);
  const acct = new Account();
  acct.run(id);
  await r.save(acct);
}

async function read(addr, tenant, id) {
  const { adapter } = repo(addr, tenant);
  const envelopes = await adapter.readEvents(`Account-${id}`);
  const out = envelopes.map((env) => ({
    event_type: env.event.eventType,
    event_version: env.event.schemaVersion,
    aggregate_type: env.metadata.aggregateType,
    aggregate_nonce: env.metadata.aggregateNonce,
    content_type: env.metadata.contentType,
    data: env.event.toJson(),
  }));
  process.stdout.write(JSON.stringify(out));
}

const [cmd, ...args] = process.argv.slice(2);
const run = { capture, write, read }[cmd];
if (!run) {
  console.error('usage: ts_peer.cjs capture <out> | write|read <addr> <tenant> <id>');
  process.exit(2);
}
run(...args).then(
  () => process.exit(0),
  (err) => {
    console.error(err);
    process.exit(1);
  }
);
