#!/bin/bash

# Secure Secrets Setup Script for Proxmox Deployment
# This script helps you create a secure .env file for your Intel NUC deployment

set -e

echo "🔐 Setting up secure secrets management for Proxmox deployment"
echo "============================================================"

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists. Please remove it first or backup and recreate:"
    echo "   mv .env .env.backup"
    exit 1
fi

# Create .env file
echo "📝 Creating .env file..."
cat > .env << 'EOF'
# Proxmox Configuration for Intel NUC Deployment
# Generated by setup-secrets.sh - DO NOT COMMIT TO VERSION CONTROL

# Proxmox API Configuration
PROXMOX_ENDPOINT=
PROXMOX_USER=
PROXMOX_TOKEN_ID=
PROXMOX_TOKEN_SECRET=
PROXMOX_INSECURE=true

# Proxmox Node Configuration
PROXMOX_NODE=pve
PROXMOX_TEMPLATE_NAME=
PROXMOX_CIUSER=ubuntu

# Network Configuration
SSH_ALLOWED_CIDRS=192.168.1.0/24
NETWORK_BRIDGE=vmbr0

# Storage Configuration
STORAGE_POOL=local-lvm
DISK_SIZE=20

# Compute Resources
VM_CPU_CORES=2
VM_MEMORY_MB=2048

# Security Settings
ALLOW_PUBLIC_GRPC=false
ALLOW_PUBLIC_DASHBOARD=false

# Environment Metadata
ENVIRONMENT=local
OWNER=developer
EOF

echo "✅ .env file created successfully!"
echo ""
echo "🔑 Now you need to edit the .env file with your actual Proxmox configuration:"
echo ""
echo "   REQUIRED VALUES:"
echo "   - PROXMOX_ENDPOINT: Your NUC's Proxmox API URL (e.g., https://192.168.1.100:8006/api2/json)"
echo "   - PROXMOX_USER: Your Proxmox user (e.g., root@pam)"
echo "   - PROXMOX_TOKEN_ID: Your API token name (e.g., terraform-provisioner)"
echo "   - PROXMOX_TOKEN_SECRET: Your API token secret UUID"
echo "   - PROXMOX_TEMPLATE_NAME: Your VM template name (e.g., ubuntu-22.04-template)"
echo ""
echo "   OPTIONAL VALUES (review and adjust as needed):"
echo "   - SSH_ALLOWED_CIDRS: Networks allowed SSH access"
echo "   - VM_CPU_CORES: CPU cores for the VM"
echo "   - VM_MEMORY_MB: Memory for the VM in MB"
echo "   - DISK_SIZE: Disk size in GB"
echo ""
echo "📝 Edit the file now:"
echo "   nano .env"
echo "   OR"
echo "   open .env"
echo ""
echo "🔒 SECURITY REMINDER:"
echo "   - NEVER commit .env to version control"
echo "   - Keep your Proxmox tokens secure"
echo "   - Use strong, unique tokens"
echo "   - Regularly rotate your tokens"
